
# creating a ServiceAccount and ClusterRoleBinding to regularly retrieve the credentials of AWS ECR

kind: ServiceAccount
metadata:
  name: registry-creds
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registry-creds
subjects:
- kind: ServiceAccount
  name: registry-creds
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io