apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: Y2hhbmdlbWU=
  AWS_SECRET_ACCESS_KEY: Y2hhbmdlbWU=
  AWS_SESSION_TOKEN: Y2hhbmdlbWU=
  aws-account: Y2hhbmdlbWU=
  aws-region: Y2hhbmdlbWU=
  aws-assume-role: Y2hhbmdlbWU=
  AWS_SESSION_TOKEN: ""
type: Opaque

