# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.23.0
networking:
  podSubnet: "10.244.0.0/16"    # canal expects --pod-network-cidr to have this as default.
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd    # tried using systemd, but failed miserably since docker expects cgroupfs. DO NOT UPGRADE!
